
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-08T19:19:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddd24f177b8fd01964ec2f9cf5fc180a7f64fdd9",
 "version": "0.3.5-1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
